### ISSUE TITLE
Default webbrowser

### ISSUE THREAD

**Issue by thelfensdrfer** [austenc/sublime-laravel-docs#1]
I use antergos with gnome. And although I changed the default browser in the settings to firefox, chrome is always opened. The webbrowser package (https://docs.python.org/3/library/webbrowser.html) is using the environment variable `BROWSER` to determine the default browser. So after changing it (for me it was in `/etc/environment`) and restarting the system, everything works as expected.

This is not an issue but maybe you could mention it in the docs?

**Comment by austenc** [comment]
Hey @thelfensdrfer thanks for the note! I wasn't sure actually how the default browser was determined but I'll add some info to the readme about that environment variable. I've been meaning to update the readme with a few other things anyway. Will leave this issue open until I've done that. Cheers!
